### ISSUE TITLE
when phase 2 release train scripts？？

### ISSUE THREAD

**Issue by Johnson-yue** [yeungchenwa/FontDiffuser#23]

**Comment by yeungchenwa** [comment]
Hi@Johnson-yue, we will release the train script within three weeks.

**Comment by Johnson-yue** [comment]
Thank you for giving the exact time！ good work about font data

**Comment by shiyongde** [comment]
watching

**Comment by yeungchenwa** [comment]
Hi @Johnson-yue @shiyongde, our training script for phase 2 has been released! Feel free to try it!
