### ISSUE TITLE
Question about the resolution.

### ISSUE THREAD

**Issue by haooxia** [yeungchenwa/FontDiffuser#26]
May I ask whether, during the comparative experiment, all the baselines were trained using the same training set as our method? The article mentions an image size of 96. Regarding DG-Font, whose resolution is limited to 80, how did you address this issue? Did you directly resize it from 80 to 96 for comparison, or did you employ other methods? Thank you.

BTW, without considering the situation of GPU memory, can we set the resolution arbitrarily for our method?

**Comment by yinminzzy** [comment]
The paper seems to have mentioned that, for a fair comparison, all the code is implemented using the official version. If the code and dataset are both based on the official version, I believe the author might have directly set the image size to 80, considering that DG-Font has limitations, and the image size is restricted to 80.

**Comment by haooxia** [comment]
> The paper seems to have mentioned that, for a fair comparison, all the code is implemented using the official version. If the code and dataset are both based on the official version, I believe the author might have directly set the image size to 80, considering that DG-Font has limitations, and the image size is restricted to 80.

I agree with your point of view, but may I ask if comparing using inconsistent resolutions would lead to unfairness? Additionally, would it be unfair if the training sets are inconsistent?

**Comment by yeungchenwa** [comment]
Hi@haooxia. Thanks for your attention. We re-collected a font generation dataset and all methods are re-trained and tested on it. We re-train and test all models based on their official code. DG-Font is trained under the image size of 80 (the same as in the official code) and we resize to 96 when testing.

**Comment by haooxia** [comment]
> Hi@haooxia. Thanks for your attention. We re-collected a font generation dataset and all methods are re-trained and tested on it. We re-train and test all models based on their official code. DG-Font is trained under the image size of 80 (the same as in the official code) and we resize to 96 when testing.

Thank you very much, I understand.

**Comment by haooxia** [comment]
BTW, without considering the situation of GPU memory, can we set the resolution arbitrarily for our method?

**Comment by yeungchenwa** [comment]
Hi@haooxia, you can set the parameter `resolution` and `content_image_size`.
