### ISSUE TITLE
Regarding the problem that the style transformation effect of English characters is relatively poor.

### ISSUE THREAD

**Issue by XieJinYan1127** [yeungchenwa/FontDiffuser#36]
Thank you for your work, I was very excited when I saw this project on [spaces], and I tried it several times in English and Chinese characters. 
The result of the experiment was that the stylistic variation of Chinese characters was very successful, but the English was very poor. I'd like to confirm to you that this is in line with expectations?

- TEST1:
![image](https://github.com/yeungchenwa/FontDiffuser/assets/111431980/500e5069-7c6e-4a63-a463-4046c27bd782)

- TEST2:
![image](https://github.com/yeungchenwa/FontDiffuser/assets/111431980/1d57a118-49e1-48bb-9f94-2994a72dfdd6)

**Comment by yeungchenwa** [comment]
Hi@XieJinYan1127, our released model is trained solely by Chinese dataset, which may lead to poor performance on large style variations of English characters. Theoretically, when FontDiffuser is trained using English dataset, it would solve the problem you mentioned.

**Comment by mwsunshine** [comment]
hi @yeungchenwa I also want to ask some questions about the training of the English letter.
1. If I add English dataset, I need to train both the phase 1 and phase 2 process, right?
2. how many fonts do you think is efficient?
3. do I need to train from scratch or refine with your model would be enough?
