### ISSUE TITLE
training about the english letters

### ISSUE THREAD

**Issue by mwsunshine** [yeungchenwa/FontDiffuser#53]
hi @yeungchenwa, thanks for your excellent work at first! 
I want to ask some questions about the training of the English letter.

If I add English dataset, I need to train both the phase 1 and phase 2 process, right?
how many fonts do you think is efficient?
do I need to train from scratch or refine with your model would be enough?

**Comment by yeungchenwa** [comment]
hi @mwsunshine Thanks for your attention! In our experiment, when you train only the phase 1, our method also can achieve excellent performance. And I think train from scratch is enough.

**Comment by mwsunshine** [comment]
cool! Thank you so much for your quick response! 
How many fonts do you think would be enough? I collect 1600+ fonts each of which contains number 1~9 and A to Z, do you think that wolud be efficient?

**Comment by yeungchenwa** [comment]
> cool! Thank you so much for your quick response! How many fonts do you think would be enough? I collect 1600+ fonts each of which contains number 1~9 and A to Z, do you think that wolud be efficient?

yeah, it's enough and efficient.

**Comment by mwsunshine** [comment]
Awesome! thank you again for your excellent work, I will train the phase 1 under your suggestion. Finger cross for a good result !
